name: CI/CD Pipeline com Docker

on:
  push:
    branches:
      - skeleton

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build e executar com Docker
        run: |
          docker build -t skeleton-portifolio-blog-app-1 .
          docker run --rm -v ${{ github.workspace }}/dist:/output skeleton-portifolio-blog-app-1

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist