name: CI/CD Pipeline com Docker

on:
  push:
    branches:
      - skeleton

# Adiciona permissões necessárias para o GitHub Actions
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build e executar com Docker
        run: |
          docker build -t skeleton-portifolio-blog-app-1 .
          docker create --name temp_container skeleton-portifolio-blog-app-1
          docker cp temp_container:/app/build ./build
          docker rm temp_container

      - name: Verificar conteúdo do build
        run: |
          echo "Conteúdo da pasta build:"
          ls -la build/

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true # Força a criação de uma nova branch limpa
          commit_message: 'Deploy: ${{ github.event.head_commit.message }}'
